### ISSUE TITLE
question about Bleu script

### ISSUE THREAD

**Issue by yaoli** [tylin/coco-caption#1]
Would the current Bleu pipeline work if some picture has more (less) than 5 captions?

For example, in eval.py
scorer.compute_score(gts, res) where gts {key, caps} and  where caps is a list of variable length, depending on how many ground truth captions a picture get. 

Also, why is the Bleu between 0 and 1?

**Comment by tylin** [comment]
Yes, it works for more or less than 5 captions.
Please read http://www.aclweb.org/anthology/P02-1040.pdf for details.

**Comment by yaoli** [comment]
Also, why is the Bleu between 0 and 1?

**Comment by hao-fang** [comment]
You can refer to the paper http://www.aclweb.org/anthology/P02-1040.pdf.
1. BP is always < 1.
2. exp(\sum w_n * log p_n) = exp(log \prod p_n^{w_n}) = \prod p_n^{w_n}, since 0 < p_n < 1 (it is the n-gram match precision), the term is also < 1.
Therefore, the BLEU is always between 0 and 1.

**Comment by yaoli** [comment]
When computing Meteor with the following script, there is an error. I
couldn't figure out what went wrong.

traceback:

[yaoli@boltzmann universal]$ python metrics.py
computing Bleu score...
{'reflen': 567, 'guess': [568, 468, 368, 268], 'testlen': 568, 'correct':
[383, 193, 97, 42]}
ratio: 1.00176366843
computing METEOR score...
Traceback (most recent call last):
  File "metrics.py", line 50, in <module>
    final_score = score(ref, sample)
  File "metrics.py", line 33, in score
    score, scores = scorer.compute_score(ref, sample)
  File "/u/yaoli/coco-caption/pycocoevalcap/meteor/meteor.py", line 42, in
compute_score
    scores.append(float(self.meteor_p.stdout.readline().strip()))
ValueError: invalid literal for float(): 6.0 7.0 3.0 4.0 1.0 1.0 0.0 0.0
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 1.0 1.0 1.0 1.0 3.0 3.0

**Comment by endernewton** [comment]
Which version of meteor did you use?  Looks like the output is not expected by the Python script.

**Comment by yaoli** [comment]
The one that comes with your package.

In your script to evaluating Meteor, we stdin.write to Meteor and then
stdout.readline to retrieve results. I've noticed sometimes stdout returns
an error. For some reason, stdin and stdout are out of sync.

I've sent you a while ago a script and two dictionaries containing refs and
samples I used to trigger the error. You can see the problem more clearly
if you could run it in your environment.
2015-4-7 上午10:21于 "Xinlei Chen" <notifications@github.com>写道：

> Which version of meteor did you use? Looks like the output is not expected
> by the Python script.
>
> Sent from my iPhone
>

**Comment by endernewton** [comment]
Resolved.
