### ISSUE TITLE
Refer to: CIDEr is 0 if eval on one sample

### ISSUE THREAD

**Issue by liuchang8am** [tylin/coco-caption#10]
Hi, in my previous Issue #9 , the provided solution seems not working.

The codes provided [here](https://github.com/ramakrishnavedantam928/coco-caption) still won't work with one image (test/ref pair).

It seems to me that, in evalscripts.py the `df_mode` parameter is not doing anything. The 'coco-val-df' in params.json is not used, and there's no code that loads the 'coco-val-df.p'.

Thanks!

**Comment by ramakrishnavedantam928** [comment]
Thanks a lot for pointing this out! Some of the local merge commits were not pushed to the repo. Could you take a [look](https://github.com/ramakrishnavedantam928/coco-caption) now and let me know if you face any other problems?

**Comment by liuchang8am** [comment]
Yeah, now everything's good. Thanks!
