### ISSUE TITLE
Wrong image id to score associations

### ISSUE THREAD

**Issue by peteanderson80** [tylin/coco-caption#12]
Hi,

I noticed that `COCOEvalCap` zip's the image ids and scores together so that individual scores can be accessed:
https://github.com/tylin/coco-caption/blob/master/pycocoevalcap/eval.py#L66

I think this is done incorrectly. The scores are ordered according to the output of multiple independent calls to `dict.keys()` in each scorer, e.g.
https://github.com/tylin/coco-caption/blob/master/pycocoevalcap/cider/cider.py#L33

However I think `dict.keys()` [returns keys in an arbitrary order](https://docs.python.org/2/library/stdtypes.html#dict.items
).

In my experience using the code, the associations in `imgToEval` were wrong, which caused me some confusion. An easy fix would be to replace each call to `dict.keys()` with `sorted(dict.keys())`.

**Comment by ozancaglayan** [comment]
You seem right, and this can invalidate the results on the evaluation server.

**Comment by tylin** [comment]
The dict.keys() is in arbitrary order but not in random.
The evaluation code uses gt.keys() to retrieve imgIds so it's fine now after the fix https://github.com/tylin/coco-caption/commit/1dcaa934c0a6a6afae53a25a16b1da6a4a5e5e05
The leaderboard result is not affected.  For details please see https://github.com/tylin/coco-caption/issues/11

**Comment by DenisDsh** [comment]
I would suggest to replace `assert(gts.keys() == res.keys()) ` with `assert(sorted(gts.keys()) == sorted(res.keys())) ` in all the metrics for the same reason.
