### ISSUE TITLE
CIDEr range

### ISSUE THREAD

**Issue by sxjzwq** [tylin/coco-caption#2]
What's the CIDEr score range? not from 0 to 1?

**Comment by ramakrishnavedantam928** [comment]
CIDEr-D scores can technically range from 0 to 10. Typically human captions would tend to score near 0.9 on the COCO Test set.

**Comment by sxjzwq** [comment]
Thanks!

**Comment by nilinykh** [comment]
@vrama91 so, how should I interpret CIDEr score then? If it's 0.9 for humans, does it mean that it is 9.0 (0.9 * 10)? Are there any standards to properly report this score? Similar to BLEU, which you normally report after multiplying with 100 (to get percentage).
