### ISSUE TITLE
Value of w_n for BLEU calculation

### ISSUE THREAD

**Issue by dr-costas** [tylin/coco-caption#20]
Hi, 

I tried to find it in the code but I could not do so. I want to ask what is the value used for w_n in the BLEU calculation equation 3 from the paper:

https://vision.cornell.edu/se3/wp-content/uploads/2015/04/1504.00325v2.pdf

**Comment by hao-fang** [comment]
w_n = 1/N in the code (i.e., it computes the standard geometric mean).
You can find more details about BLEU in http://www.aclweb.org/anthology/P02-1040.pdf.
