### ISSUE TITLE
Add SPICE

### ISSUE THREAD

**Issue by peteanderson80** [tylin/coco-caption#24]
Hi,

Thank you for this code base. The SPICE metric seems to be getting quite a bit of use, including on the [coco leaderboard](http://mscoco.org/dataset/#captions-leaderboard). Rather than maintaining a [separate fork](https://github.com/peteanderson80/coco-caption) that includes the SPICE metric, can I create a pull request to include it in this repo?

Thanks

**Comment by tylin** [comment]
Yes, Peter. Thanks for brining this up. Please create a pull request to add SPICE to this repo.

**Comment by PavlosMelissinos** [comment]
Hi @peteanderson80, thanks for the offer. Any progress?

**Comment by peteanderson80** [comment]
My apologies, I will not get to this until after the CVPR deadline (Nov 15). However code in the [fork](https://github.com/peteanderson80/coco-caption) can be used for the SPICE metric.

**Comment by PavlosMelissinos** [comment]
Hey, that's ok, I'll try to prepare/submit a PR here if that's ok with you.
Also, I didn't realize you're the author of SPICE before. Thanks for giving us a great metric! :)

**Comment by peteanderson80** [comment]
Yes please feel free to go ahead, and thanks!

**Comment by peteanderson80** [comment]
I did see any other PR so I've finally done this: #30
