### ISSUE TITLE
can not get the result showed in demo

### ISSUE THREAD

**Issue by songjun54cm** [tylin/coco-caption#3]
Hi, I am running the demo script "cocoEvalCapDemo.py" but the result I have got was as follows:

>loading annotations into memory...
>0:00:00.654000
>creating index...
>index created!
>Loading and preparing results...
>DONE (t=0.03s)
>creating index...
>index created!
>tokenization...
>PTBTokenizer tokenized 61268 tokens at 525144.89 tokens per second.
>PTBTokenizer tokenized 10892 tokens at 160108.14 tokens per second.
>setting up scorers...
>computing Bleu score...
>{'reflen': 9855, 'guess': [9893, 8893, 7893, 6893], 'testlen': 9893, 'correct':
>[5732, 2510, 1043, 423]}
>ratio: 1.00385591071
>Bleu_1: 0.579
>Bleu_2: 0.404
>Bleu_3: 0.279
>Bleu_4: 0.191
>computing METEOR score...
>METEOR: 0.195
>computing Rouge score...
>ROUGE_L: 0.396
>computing CIDEr score...
>CIDEr: 0.600
>CIDEr: 0.600
>Bleu_4: 0.191
>Bleu_3: 0.279
>Bleu_2: 0.404
>Bleu_1: 0.579
>ROUGE_L: 0.396
>METEOR: 0.195
.....

the value of Bleu and other metrics are different from the value showed in the ipynb file "cocoEvalCapDemo.ipynb"  I am not sure what is the problem. Is the ipynb file out of date or something others???

**Comment by hao-fang** [comment]
I think the ipynb file is out of date. I can get the same BLEU using the example and they look reasonable to me. Scores at 1 means exactly match, which I don't think it's true in the demo data.

Thanks,
Hao

**Comment by tylin** [comment]
The IPython demo file was updated and html and python were removed for consistency.
