### ISSUE TITLE
Blue score looks different in formula

### ISSUE THREAD

**Issue by silvioOlivastri** [tylin/coco-caption#39]
I don't understand two line of code about BLEU score:

1) https://github.com/tylin/coco-caption/blob/master/pycocoevalcap/bleu/bleu_scorer.py#L250
2) https://github.com/tylin/coco-caption/blob/master/pycocoevalcap/bleu/bleu_scorer.py#L252

They are very different if you look the original formula (3) in https://vision.cornell.edu/se3/wp-content/uploads/2015/04/1504.00325v2.pdf

Can you help me to explain why?

**Comment by hao-fang** [comment]
Since w_n is constant, Formula (3) is equivalent to b(C, S) (\prod_n CP_n)^{1/N}, which is the way we implement the codes.
