### ISSUE TITLE
would the system work if refs has only one caption

### ISSUE THREAD

**Issue by yaoli** [tylin/coco-caption#4]
I notice that coco-caption/pycocoevalcap/bleu/bleu.py has a line 'assert(len(ref)) > 1', which in my case, I have only one ref per image. Would the evaluation pipeline work if I just simply commented out this line? If not could you point out the necessary modification of the code to make it compatible with only one ref?

Thanks.

**Comment by hao-fang** [comment]
It should be safe to comment out that line.

Thanks,
Hao
