### ISSUE TITLE
Meteor metric crash

### ISSUE THREAD

**Issue by lvapeab** [tylin/coco-caption#6]
Hi, 

I'm trying to use the METEOR metric but I'm facing some issues: The `pycocoevalcap/meteor/meteor.py` crashes at line [42](https://github.com/tylin/coco-caption/blob/master/pycocoevalcap/meteor/meteor.py#L42-L43), because `self.meteor_p.stdout.readline()` returns an empty string:

`` ValueError: could not convert string to float: ``

It seems that the `meteor_p` subprocess doesn't receive the `eval_line` at line [40](https://github.com/tylin/coco-caption/blob/master/pycocoevalcap/meteor/meteor.py#L40). I've seen an issue #1 that also had a similar problem with the Meteor script, but I don't know how it was solved or if it was due to different reasons than mine.

I have the same problem either by running  `cocoEvalCapDemo.ipynb` and by running the metrics on my own data. I use the ``meteor-1.5.jar`` that is included in your package. If I use it directly from the command line (without the python wrapper), it works. The rest of metrics work properly.

Do you have any ideas/suggestions about this error?

Thank you very much

**Comment by endernewton** [comment]
Hey,

Are you using the standard way to call the evaluation code? Some time ago I
wrote a version that can give you an example to call the evaluation code
(that works on my side at least). Check out this.

Hope it helps!

-Xinlei

**Comment by lvapeab** [comment]
Thanks for your quick reply :)

Yes, I'm using what I think is the standard way (the one used in the IPython notebook). Have you attached something or linked to somewhere? Because I cannot see it :see_no_evil:

**Comment by hunter-87** [comment]
i'm having the same problem, have you solved it?

**Comment by hunter-87** [comment]
ok, i think i've found the problem, it lies in METEOR jar
if your system locale, like mine, use the comma as double separator, when we call EVAL the program expect doubles in the form of 1,0 but instead the output from the SCORE use dot, ie 1.0

a quick fix is change your locale settings or add in meteor.py a system env like this:

```
def __init__(self):
        d = dict(os.environ.copy())
        d['LANG'] = 'C'
        self.meteor_cmd = ['java', '-jar', '-Xmx2G', METEOR_JAR, \
                '-', '-', '-stdio', '-l', 'en', '-norm']
        self.meteor_p = subprocess.Popen(self.meteor_cmd, \
                cwd=os.path.dirname(os.path.abspath(__file__)), \
                stdin=subprocess.PIPE, \
                stdout=subprocess.PIPE, \
                stderr=subprocess.PIPE, env=d)
        # Used to guarantee thread safety
        self.lock = threading.Lock()

```

**Comment by lvapeab** [comment]
Ok, that was the problem. Thank you so much!

**Comment by endernewton** [comment]
I will update the version! Thanks for that.

-Xinlei

**Comment by johnwlambert** [comment]
Hi, I've been evaluating the COCO captions and he METEOR metric does not seem to be fixed in the latest release of the py-coco evaluator. I still get the same error: "ValueError: could not convert string to float." The CIDEr, BLEU, and Rouge-L ones work perfectly, however

**Comment by fabudlx** [comment]
Same error as described by @hunter-87, but his fix did not work for me. I worked around the issue by replacing : 

`self.meteor_p.stdin.write('{}\n'.format(eval_line))` 

with 

`self.meteor_p.stdin.write('{}\n'.format(eval_line).replace('.',','))`
