### ISSUE TITLE
Is there demo code to convert annotations, eg, Flickr8K, to COCO format?

### ISSUE THREAD

**Issue by playerkk** [tylin/coco-caption#7]
I tried to write my own but can not make it work. Thanks.

**Comment by kracwarlock** [comment]
I have a script that I use for my experiments:
https://gist.github.com/kracwarlock/c979b10433fe4ac9fb97

If you convert custom annotations to the format specified in the script, it works.

**Comment by ramakrishnavedantam928** [comment]
I recently forked this repository to use the MSCOCO evaluation codes with arbitrary input data, free of the coco annotations: 
https://github.com/ramakrishnavedantam928/coco-caption
