### ISSUE TITLE
CIDEr is 0 if eval on one sample

### ISSUE THREAD

**Issue by liuchang8am** [tylin/coco-caption#9]
If evaluate on only one sample, say a dummy test sample extracted from "captions_val2014.json", call the eval codes will always give 0 CIDEr score. If given more than one sample, the CIDEr works normal.

Other metrics are valid given one sample except for CIDEr.

Attached test outputs:
loading annotations into memory...
0:00:00.760903
creating index...
index created!

[{u'image_id': 203564, u'id': 37, u'caption': u'A bicycle replica with a clock as the front wheel.'}]

using 1/1 predictions
Loading and preparing results...     
DONE (t=0.03s)
creating index...
index created!
tokenization...
PTBTokenizer tokenized 60 tokens at 1344.11 tokens per second.
PTBTokenizer tokenized 11 tokens at 281.16 tokens per second.
setting up scorers...
computing Bleu score...
{'reflen': 10, 'guess': [10, 9, 8, 7], 'testlen': 10, 'correct': [10, 9, 8, 7]}
ratio: 0.9999999999
Bleu_1: 1.000
Bleu_2: 1.000
Bleu_3: 1.000
Bleu_4: 1.000
computing METEOR score...
METEOR: 1.000
computing Rouge score...
ROUGE_L: 1.000
computing CIDEr score...
CIDEr: 0.000

**Comment by ramakrishnavedantam928** [comment]
CIDEr estimates TFIDF from a corpus of sentences and uses it for evaluation. Thus, it does not work if only sentences for only one image are provided. You can use the code [here](https://github.com/ramakrishnavedantam928/coco-caption) to use the IDF values from MSCOCO instead, and still do evaluation with one data point.

**Comment by liuchang8am** [comment]
Thanks, will check it out.

**Comment by liuchang8am** [comment]
@ramakrishnavedantam928 It seems that the df_mode parameter in evalscripts.py Line38 isn't doing anything?
btw, it seems "import os" should be added in the code.

**Comment by liuchang8am** [comment]
@ramakrishnavedantam928 Hi, the code provided [https://github.com/ramakrishnavedantam928/coco-caption](here) seems not working with one sample. The `df_mode` in evalscripts.py seems not doing anything. The code still gives 0 CIDEr score with the 'idf' set to 'coco-val-df'.

btw, in evalscripts.py, it seems need to add a 'mport os'.

Plz help, thanks!

**Comment by czy-orange** [comment]
> CIDEr estimates TFIDF from a corpus of sentences and uses it for evaluation. Thus, it does not work if only sentences for only one image are provided. You can use the code [here](https://github.com/ramakrishnavedantam928/coco-caption) to use the IDF values from MSCOCO instead, and still do evaluation with one data point.

So even the same sentence along with same references may give different CIDEr score, if the whole corpus changes?
